# Generated by Django 4.2.1 on 2023-06-03 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_rename_tasks_task"),
    ]

    operations = [
        migrations.RemoveField(model_name="task", name="completed",),
        migrations.RemoveField(model_name="task", name="date",),
        migrations.RemoveField(model_name="task", name="description",),
        migrations.RemoveField(model_name="task", name="project",),
        migrations.RemoveField(model_name="task", name="starred",),
    ]
