# Generated by Django 4.2.1 on 2023-06-03 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Tasks", new_name="Task",),
    ]
