# Generated by Django 4.2.1 on 2023-06-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_task_completed_task_date_task_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="date",
            field=models.DateField(default="14/06/2021"),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.CharField(default="None", max_length=500),
        ),
        migrations.AlterField(
            model_name="task",
            name="project",
            field=models.CharField(default="None", max_length=200),
        ),
    ]
