# Generated by Django 4.2.1 on 2023-06-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_alter_task_date_alter_task_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task", name="date", field=models.DateField(),
        ),
    ]
